name: Build jar-file of latest version containing all dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: # only build new jar file if pom.xml or java sources have changed
      - pom.xml
      - src/main/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run idealo github-app-token-generator
        uses: idealo/github-app-token-generator@v1.0.1
        id: get-token
        with:
          private-key: ${{ secrets.IDEALO_BOT_GH_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.IDEALO_BOT_GH_APP_ID }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # You can choose other distributions like 'zulu' or 'temurin'
          java-version: '11'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and package JAR with dependencies
        run: mvn clean package

      - name: Move JAR to latest-version folder
        run: |
          mkdir -p latest-version
          mv target/*-jar-with-dependencies.jar latest-version/mongodb-performance-test.jar

      - name: Commit jar file to repository and add version tag
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          git add latest-version/mongodb-performance-test.jar
          git commit -m "Add latest version ($VERSION) of mongodb-performance-test.jar"
          
          # Delete the local tag if it exists, then recreate it
          git tag -d "v$VERSION" || true  # Ignore if the tag doesn't exist
          git tag -a "v$VERSION" -m "Tagging version $VERSION"
          
          git push origin master
          git push --tags
          
          echo "### Version updated to $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "The [latest-version/mongodb-performance-test.jar](https://github.com/idealo/mongodb-performance-test/tree/master/latest-version/mongodb-performance-test.jar) is now $VERSION" >> $GITHUB_STEP_SUMMARY
